blank_issues_enabled: false
contact_links:
  - name: Discussões & Dúvidas da Comunidade
    url: https://github.com/murphases/media-optimizer/discussions
    about: Faça perguntas e interaja com outros usuários e colaboradores.
